### ISSUE TITLE
Creating a budget crashes and burns

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisdb#102]
![screenshot from 2015-07-21 20 45 30](https://cloud.githubusercontent.com/assets/7164637/8809632/3a65e0f6-2fea-11e5-96c3-b55abd6693a5.png)

**Comment by stefanmajoor** [comment]
Might have to do with this commit: https://github.com/GEWIS/gewisdb/commit/b5bee60ed481c812e57ba4079b18492ce4549dc5

**Comment by stefanmajoor** [comment]
After some more research the following commit is to blame:

**Comment by kokx** [comment]
e14ce85 was introduced to deal with the newer Zend Framework version handling things differently.

Run `composer install` to fix your issues.

**Comment by stefanmajoor** [comment]
```composer install``` didn't work the first time. Removed vendor map and did ```composer install``` again, and then it worked.
