### ISSUE TITLE
Ledenpagina: mogelijkheid tot alle gegevens weergeven

### ISSUE THREAD

**Issue by rikrutjens** [GEWIS/gewisdb#115]
Een kleine selectie weergeven is vaak handig en ruimtebesparend enzo, maar soms is het ook handig om alle data (dus alle 7800 leden) te zien. Ik zou graag een mogelijkheid hiertoe zien.

**Comment by kokx** [comment]
Deze bestaat al, maar niet rechtstreeks. Daarvoor kun je de volgende query invoeren:

```
SELECT m FROM db:Member m
```
