### ISSUE TITLE
Automatic cleanup of reportdb

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisdb#118]
Right now, members and decisions will be added to the reportdb. However, they will not be removed. The easiest way to solve this (and possible errors) is to simply TRUNCATE all the tables in the reportdb every time.

This means that between 0:30 and 2:00, the secretary cannot run queries in the report database. Possibly, this should be adjusted as well, or guarded in some way.

**Comment by tomudding** [comment]
There is currently no reason to implement something like this, as most updates to the entities are propagated (though not everything, see for example #147). Furthermore, completely regenerating the report database will cause foreign key constraint failures in GEWISWEB as the ids of organs shift (or change).
