### ISSUE TITLE
Prio: Genderkeuze in db

### ISSUE THREAD

**Issue by rikrutjens** [GEWIS/gewisdb#119]
Zoals besproken met Pieter.

Momenteel kun je in de db enkel kiezen tussen man en vrouw.

Gelieve te zorgen dat dit man, vrouw of niet gespecificeerd wordt (Kit gaf met redelijk wat druk aan dat ze niet wil dat het "anders" of "overig" heet)

**Comment by kokx** [comment]
Dit bestaat al wel correct in het inschrijfformulier. Het wijzigingsformulier voor de secretaris zelf moet nog worden aangepast.

**Comment by stefanmajoor** [comment]
Nu staat het er toch als "Anders" in, ondanks @rikrutjens comment.

Dit moet nog even veranderd worden naar "niet gespecificeerd"

(Dit doe ik vanavond)
