### ISSUE TITLE
Prevent duplicate members from being added

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisdb#126]
When adding a member, check if the name + email combination already exists in the database. In that case, pretend like nothing is wrong, and print the _original_ information that was inputted.

However, this information shouldn't be displayed for members that have been registered more than a week ago.

**Comment by rinkp** [comment]
+make email address unique since they'll be used for logins.

**Comment by tomudding** [comment]
> +make email address unique since they'll be used for logins.

This is implemented just not in the correct way (it is currently case sensitive).
