### ISSUE TITLE
Automatically print completed registrations

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisdb#128]

**Comment by kokx** [comment]
What kinda needs to be done for that:

- [ ] Create printable page for any member
- [ ] Install tool on the server that can 'print' an HTML page to PDF (@jszanto)
- [ ] Make the server able to print PDF's (@jszanto)
- [ ] Patch this all together.

**Comment by rinkp** [comment]
I don't think this is necessary anymore. In the past this was used to physically sign for SEPA Direct Debit
