### ISSUE TITLE
Typo in (unused) `AnnotationBuilder` factory

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#153]
I don't think the `AnnotationBuilder` is used anywhere in the Report module, but it does contain a typo (`$sl` instead of `$sm`).

https://github.com/GEWIS/gewisdb/blob/6e7ca59e3fd6292a9c4e7a09b103e34a2e9ef4dd/module/Report/Module.php#L61-L63

**Comment by Koen1999** [comment]
If we used it we probably noticed xD
