### ISSUE TITLE
Add setting to remove IBAN/SEPA from enrolment form

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisdb#184]
Throughout the year, the IBAN and SEPA part of the join.gewis.nl form is not really needed. Would it be possible to remove this part of the form a few weeks after the introduction week? This also makes a very clear distinction between SEPA transactions and manual transactions for the secretary and the treasurer. :)

**Comment by tomudding** [comment]
Functionality added in 0a10d05d92d4d384180c8b121b9c0cc2aba10257.

However, this has to be done by the ABC and not the secretary, I know this is inconvenient but adding massive amounts of code for a single checkbox is more inconvenient. [I tried to create a generic wrapper](https://github.com/GEWIS/gewisdb/commit/f58dc1610d0d90b211f0a6dbb352089f3c8adfcf) that would allow for more different settings to be added in the future, but that just massively increased the complexity.
