### ISSUE TITLE
Cannot approve prospective member without IBAN when IBAN is required

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#205]
### Current behaviour

When a prospective member does not have an IBAN but it is required they cannot be approved.

### Desired behaviour

Even though the prospective member does not have an IBAN they should be approvable.

### Steps to reproduce

Create a prospective member without IBAN (when it is not required), then make IBANs required, finally try to approve the prospective member.

### Database version

22e06a4

### Other information

_Originally reported by Daan._

**Comment by rinkp** [comment]
```php
$form = $this->getMemberForm();
$inputFilter = $form->getInputFilter();
$inputFilter->remove('iban');
$inputFilter->remove('signature');
$inputFilter->remove('signatureLocation');
$inputFilter->remove('agreediban');
$form->setInputFilter($inputFilter);
```
This?

**Comment by tomudding** [comment]
Yes that should fix it, but as long as we do not require SEPA (like it currently is) we do not have to fix it. As we will have implemented Stripe by then.
