### ISSUE TITLE
Upgrade to PHP 8.2

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#212]
On December 8, 2022 PHP 8.2 will be released. There are a few things that should be checked before hand:

- no dynamic properties (I do not think we use this),
- removing partially callables (mostly used for callbacks in forms) as they are deprecated,
- ensuring correct return types when returning new instances of `DateTime(Immutable)`, and
- removing incorrect string interpolation of the form `"${some_variable}"` (but I do not think we use this).

Additionally, we have constructors that look like this:

```php
class SomeClass
{
    public function __construct(
        private readonly SomeType $var,
        private readonly AnotherType $anotherVar,
    ) {
    }

    // (...)
```

They can be changed to (only works for classes of which all properties are `readonly`):

```php
readonly class SomeClass
{
    public function __construct(
        private SomeType $var,
        private AnotherType $anotherVar,
    ) {
    }

    // (...)
```

**Comment by rinkp** [comment]
> only works for classes of which all properties are `readonly`

Additionally, for PHP, `readonly` classes may not be extended by non-`readonly` classes (so both parent and child must be `readonly`/non-`readonly`)
