### ISSUE TITLE
Subscription form is partially Dutch-only

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#273]
### Current behaviour

![image](https://user-images.githubusercontent.com/17340320/228833206-d52a1acb-5482-4bc7-b3c7-44fef6067b42.png)

### Steps to reproduce

Go to https://join.gewis.nl/

### Database version

1908262f5deca89b83f9f498648878b07ad20c42

**Comment by tomudding** [comment]
Only `Studie` is still in Dutch, I will fix this later today.

**Comment by tomudding** [comment]
> Only `Studie` is still in Dutch, I will fix this later today.

Fixed in 0f465bd.
