### ISSUE TITLE
Some graduates do not get action link to renew graduate status

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#296]
### Current behaviour

Last year when managing graduates I marked most of them hidden, the exact reasoning for this I have long forgotten. However, this means that these graduates do not get an action link send to them to renew their graduate status:

https://github.com/GEWIS/gewisdb/blob/a0e709da14120168ce4918eaf6ca6caf7f734b4a/module/Checker/src/Mapper/Member.php#L127-L133

On top of that, on renewal, the hidden state is never removed:

https://github.com/GEWIS/gewisdb/blob/a0e709da14120168ce4918eaf6ca6caf7f734b4a/module/Database/src/Controller/MemberController.php#L96-L101

### Steps to reproduce

1. Add graduate with expiring state and set hidden
2. Send action links
3. Access action link and renew graduate status
4. Graduate is still hidden

### Database version

 a0e709d

**Comment by rinkp** [comment]
This is no longer an issue
