### ISSUE TITLE
Refund prospective member when declining membership

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#313]
### What would you like?

After payment the secretary can still decline prospective members (e.g. if they study at another department); in those cases, the payment should be refunded automatically. We must check a payment was not refunded before, but fortunately Stripe does not allow refunds for more than the initial payment.

### Why is this needed?

This is needed to allow for accidental duplicate registrations or registrations from non-students which have happened in the past.

**Comment by tomudding** [comment]
I was wondering whether we would want this to be implemented or that this is just something that the treasurer and secretary do manually.

Either way, there should be a confirmation modal on the delete action to make sure you do not accidentally remove a prospective member (and while we are at it, also add one for the approval).
