### ISSUE TITLE
Registration form Stripe submission conflicts with CSP in Chromium-based browsers

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#324]
### Current behaviour

When submitting the join form for another person a second time, Submit won't redirect the first time properly, the second time will cause a "Someone is already registered with this email address" message. 

Cannot say for sure that it always does this

It can be solved by restarting the browser. 

### Steps to reproduce

Register, pay, go to the form again, attempt registration again, it won't work

### Database version

53a6ef24

**Comment by tomudding** [comment]
Is the second registration is with a different e-mail address?

**Comment by rinkp** [comment]
> Is the second registration is with a different e-mail address?

Yes

**Comment by tomudding** [comment]
I cannot reproduce this locally or on the test instance (in Firefox).

**Comment by tomudding** [comment]
I can reproduce it in Edge in kiosk mode

**Comment by tomudding** [comment]
![image](https://github.com/GEWIS/gewisdb/assets/4983571/f4632ff5-854d-4981-a276-c1d1a77fa34a)

**Comment by tomudding** [comment]
![image](https://github.com/GEWIS/gewisdb/assets/4983571/ae771a5f-bdc0-4b88-a1a0-6de98628bab2)
Chromium issue, same reason why the website uses an intermediate webpage for JWT auth to redirect user.

**Comment by tomudding** [comment]
I do not have the time to fix this, however, I have explained to Rink how to do it.
