### ISSUE TITLE
Expired checkout after paid checkout causes strange behaviour

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#332]
### Current behaviour

Currently, if there is both an expired and a paid session, the ordering is random (not timestamp based) and the Expired entry is fetched after the Paid entry, the cash approval mode is shown. The user **is** shown in the Paid column.

![image](https://github.com/GEWIS/gewisdb/assets/17340320/b492a53f-f15b-4f1d-b89d-a851bebf62ff)

### Steps to reproduce

Do a lot of row edits in checkout and wait for Postgres to optimize itself and change the ordering.

### Database version

4e00cc3f

**Comment by tomudding** [comment]
Personally I find this a non-issue but it can be easily resolved by adding https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/attributes-reference.html#attrref_orderby to https://github.com/GEWIS/gewisdb/blob/master/module/Database/src/Model/ProspectiveMember.php#L168.

**Comment by rinkp** [comment]
> Personally I find this a non-issue but it can be easily resolved by adding https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/attributes-reference.html#attrref_orderby to https://github.com/GEWIS/gewisdb/blob/master/module/Database/src/Model/ProspectiveMember.php#L168.

I think showing the cash form occassionally for members who already paid causes the secretary to ignore this when accidentally clicking on an unpaid member, so I'll fix this

**Comment by tomudding** [comment]
> > Personally I find this a non-issue but it can be easily resolved by adding https://www.doctrine-project.org/projects/doctrine-orm/en/2.16/reference/attributes-reference.html#attrref_orderby to https://github.com/GEWIS/gewisdb/blob/master/module/Database/src/Model/ProspectiveMember.php#L168.
> 
> I think showing the cash form occassionally for members who already paid causes the secretary to ignore this when accidentally clicking on an unpaid member, so I'll fix this

Ah I missed the part about form, the it should definitely be fixed.
