### ISSUE TITLE
Use real year instead of "week of year" year

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#360]
### Current behaviour

We currently use 'Y', but should use 'y' (https://unicode-org.github.io/icu/userguide/format_parse/datetime/)

```php
<?php

$formatter = new IntlDateFormatter(
            'nl_NL', // yes, hardcoded :D
            IntlDateFormatter::NONE,
            IntlDateFormatter::NONE,
            date_default_timezone_get(),
            null,
            'd MMMM y',
        );
echo $formatter->format(new \DateTime("2000-01-01"));
```

### Steps to reproduce

.

### Database version

a7b15357d2d43b70c72a7853b12ac00ce964c0b0

**Comment by tomudding** [comment]
Present in the following files:

https://github.com/GEWIS/gewisdb/blob/a7b15357d2d43b70c72a7853b12ac00ce964c0b0/module/Database/src/Model/SubDecision/Budget.php#L207
https://github.com/GEWIS/gewisdb/blob/a7b15357d2d43b70c72a7853b12ac00ce964c0b0/module/Database/src/Model/SubDecision/Board/Installation.php#L147
https://github.com/GEWIS/gewisdb/blob/a7b15357d2d43b70c72a7853b12ac00ce964c0b0/module/Database/src/Model/SubDecision/Board/Release.php#L121
https://github.com/GEWIS/gewisdb/blob/a7b15357d2d43b70c72a7853b12ac00ce964c0b0/module/Database/src/Model/SubDecision/Key/Granting.php#L109
https://github.com/GEWIS/gewisdb/blob/a7b15357d2d43b70c72a7853b12ac00ce964c0b0/module/Database/src/Model/SubDecision/Key/Withdrawal.php#L116
and
GH-357
