### ISSUE TITLE
`Form` requires new `@extends`

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#366]
### Current behaviour

The latest version of `laminas/laminas-form` (used when developing) has introduced a new template variable on `Form`s. This requires a new `@extends` on our end.

### Desired behaviour

This new "payload" cannot just be simply added to the forms, we must carefully check which types are actually applicable (i.e. only an object or a combination of an array and an object).

### Steps to reproduce

Run Psalm on the latest development branch.

### Database version

develop

**Comment by tomudding** [comment]
First noticed in GH-357.

**Comment by rinkp** [comment]
In GH-368 we discussed to not do this because it does not benefit us and only complicates things.
