### ISSUE TITLE
Deleting a member with audit entries should remove those entries

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#369]
### Current behaviour

Hard deleting a member will cause the notes to be deleted due to the cascading
Soft deletes keep the original entries

### Steps to reproduce

Delete a member who is referenced in one or more decisions 

### Database version

https://github.com/GEWIS/gewisdb/commit/50f20b8b75d1731b679fb6852d667241479f0101

**Comment by tomudding** [comment]
Good catch! Relatively easy to fix:

```diff
@@ -1 +1 @@
    public function clear(MemberModel $member): void
    {
        foreach ($member->getAddresses() as $address) {
            $this->getMemberMapper()->removeAddress($address);
        }
+
+        foreach ($member->getAuditEntries as $auditEntry) {
+            $this->getAuditMapper()->remove($auditEntry);
+        }
```
