### ISSUE TITLE
Making a `Member` `external` should use `membershipEndsOn` at the end of the current association year.

### ISSUE THREAD

**Issue by tomudding** [GEWIS/gewisdb#420]
### Current behaviour

Manually changing someone's membership type to `external` sets the `membershipEndsOn` to the start of the current association year.

### Desired behaviour

The `membershipEndsOn` should be at the end of the current association year for `external`s.

### Steps to reproduce

Make someone `external` observe `membershipEndsOn` is in the past instead of the future.

### Database version

latest

### Other information

Follows from ABC-2407-095.

**Comment by rinkp** [comment]
Maybe we should rethink the entire UI of showing this and extending this. I am thinking of adding a date field when clicking update/renew

**Comment by tomudding** [comment]
> Maybe we should rethink the entire UI of showing this and extending this. I am thinking of adding a date field when clicking update/renew

I do not think this is necessary; perhaps the form needs some clarification, but with this fixed, everything behaves the same. All changes are applied as if this was the case on July 1st (start of the current association year).
