### ISSUE TITLE
Keyholder decisions expire one day early

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisdb#432]
### Current behaviour

The keyholder check does not understand "tot en met", which means that the interpretation of the keyholder decisions is off by a day

Relevant code: https://github.com/GEWIS/gewisdb/blob/main/module/Report/src/Model/Keyholder.php#L172-L176

## Example
Decision text: "John Doe krijgt een sleutelcode van GEWIS tot en met 1 september 2024."

This decision is in line with the key policy with GEWIS which allows the key to expire ON the 1st of September:

> The possible granted access has a maximum duration of one year, but always ends on or before September 1st of the next association year.

However, because September 1st is encoded at "2024-09-01T00:00:00", that means that on September 1st, the granted access is no longer considered "current"

### Desired behaviour

Include the end date, because the decision text is "tot **en met**"

### Database version

08dbbe8c1049d84e750f199a5d1ace4163ff6c22

**Comment by tomudding** [comment]
GEWISWEB does it correctly:

https://github.com/GEWIS/gewisweb/blob/09b1556e422f50ce641dc46072f71f2a871468b4/module/Decision/src/Model/Member.php#L804

Should be quite easy to fix by making the argument of [`$now`](https://github.com/GEWIS/gewisdb/blob/08dbbe8c1049d84e750f199a5d1ace4163ff6c22/module/Report/src/Model/Keyholder.php#L170) `today`.
