### ISSUE TITLE
Creating a budget displays error

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisdb#67]
When creating a budget the following error occurs:

```
Notice: Undefined index: changes in /var/www/html/gewisdb/module/Database/src/Database/Hydrator/Budget.php on line 41
```

The budget is made

**Comment by stefanmajoor** [comment]
Was an issue that the with changes radio button was not selected. This has been fixed

**Comment by kokx** [comment]
Goed bezig.
