### ISSUE TITLE
Replace LOWER() LIKE with ILIKE in queries

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisdb#69]
Postgresql has the ILIKE comparison to search for case insensitive words

See http://www.postgresql.org/docs/8.3/static/functions-matching.html

This makes the current ugly hack redundand

**Comment by kokx** [comment]
Though PostgreSQL does indeed have that feature, Doctrine does not. Which makes it way too much work to implement it, especially because there is no real gain here.
