### ISSUE TITLE
Statistieken op frontpage

### ISSUE THREAD

**Issue by kokx** [GEWIS/gewisdb#75]
Zet de volgende statistieken op de frontpage:
- Aantal leden
- Aantal actieve leden
- ???

**Comment by BorBorBor** [comment]
- Percentage tussen die twee die je noemde
- Verhouding bachelor / master en wiskunde / informatica
- Hoeveel x groter dan Japie we zijn (real-time)
- Een feature om makkelijk aan dit lijstje toe te voegen

**Comment by kokx** [comment]
Heeft de Japie ledenadministratie ook een API?

**Comment by kokx** [comment]
- man / vrouw verhouding
- man / vrouw verhouding onder actieve leden
